import type { WheelEvent } from 'react';
import { Cube2DRenderer } from '../renderer2d/Cube2DRenderer';
import { Cube2DGameController } from './Cube2DGameController';
import { Cube2DVisualEffects } from './Cube2DVisualEffects';
import { GameResultDialog } from './GameResultDialog';
import { CUBE_ENDGAME_STATUSES, cubeEndgameStatusLabel, useCube2DGame } from './useCube2DGame';
import './manual-endgame.css'; import './cube2d-preview.css'; import './cube2d-game-flow.css'; import './cube2d-game.css';

export interface Cube2DGameProps { readonly controller: Cube2DGameController; readonly onRequestNewGame: () => void; }
export function Cube2DGame({ controller, onRequestNewGame }: Cube2DGameProps) {
  const g = useCube2DGame(controller);
  const wheel = (event: WheelEvent<HTMLDivElement>) => { event.preventDefault(); g.setZoom(g.zoom - event.deltaY * 0.0008); };
  return <section className="cube-2d-game" aria-label="Cube 2D game">
    <header className="cube-2d-game__toolbar">
      <div className="cube-2d-game__summary" aria-label="Cube game status"><strong>{controller.size}×{controller.size} Cube 2D</strong><span>Move {g.vm.moveNumber}</span><span>{g.vm.currentPlayer === 'black' ? 'Black' : 'White'} to move</span><span>{g.vm.ruleSet === 'chinese' ? 'Chinese' : 'Japanese'} rules</span><span>Komi {g.vm.komi}</span><span>White Captured {g.vm.captures.black}</span><span>Black Captured {g.vm.captures.white}</span></div>
      <div className="cube-2d-game__view-controls"><button type="button" aria-label="Zoom out Cube 2D" onClick={() => g.setZoom(g.zoom - .1)}>−</button><span className="cube-2d-game__zoom-value" aria-label="Cube zoom">{Math.round(g.zoom * 100)}%</span><button type="button" aria-label="Zoom in Cube 2D" onClick={() => g.setZoom(g.zoom + .1)}>+</button><button type="button" onClick={() => g.setZoom(1)}>Reset zoom</button><button type="button" aria-pressed={g.showMoveNumbers} onClick={() => g.setShowMoveNumbers((value) => !value)}>Move numbers</button></div>
    </header>
    <div className="cube-2d-game__board-row">
      <div className="cube-2d-navigation" aria-label="Cube 2D navigation"><button type="button" aria-label="Move cube up" disabled={Boolean(g.transition)} onClick={() => g.navigate('up')}>↑</button><div><button type="button" aria-label="Move cube left" disabled={Boolean(g.transition)} onClick={() => g.navigate('left')}>←</button><button type="button" aria-label="Move cube right" disabled={Boolean(g.transition)} onClick={() => g.navigate('right')}>→</button></div><button type="button" aria-label="Move cube down" disabled={Boolean(g.transition)} onClick={() => g.navigate('down')}>↓</button></div>
      <div className="cube-2d-game__viewport" onWheel={wheel}><div className="cube-2d-game__scaled-stage" style={{ width: `${760 * g.zoom}px`, height: `${570 * g.zoom}px` }}><div className="cube-2d-stage cube-2d-game__stage" style={{ transform: `scale(${g.zoom})` }}>
        <Cube2DRenderer layout={g.layout} transition={g.transition ?? undefined} onVerticalAnchorColumnChange={g.moveAnchor} viewModel={g.vm} hoveredPointId={g.hoveredPoint} hoverStatus={g.hoverStatus} showMoveNumbers={g.showMoveNumbers} inputDisabled={Boolean(g.transition) || g.vm.phase === 'finished'} onPointHover={g.hover} onPointActivate={(point) => void g.activate(point)} />
        <Cube2DVisualEffects layout={g.layout} finalScore={g.vm.finalScore} finalClassification={g.finalClassification} endgameGroups={g.groups} decisions={g.decisions} selectedGroupId={g.selectedGroup} hoveredGroupId={g.hoveredGroup} capturedStones={[]} />
      </div></div></div>
    </div>
    <div className="cube-2d-game__actions" role="group" aria-label="Cube game controls"><button className="cube-2d-game__action cube-2d-game__action--primary" type="button" disabled={g.vm.phase !== 'playing' || g.passGuarded} onClick={() => void g.pass()}>{g.vm.phase === 'playing' && g.vm.consecutivePasses === 1 ? 'Pass (1)' : 'Pass'}</button><button className="cube-2d-game__action" type="button" disabled={!controller.canRedo()} onClick={() => void g.run(() => controller.redo())}>Redo</button><button className="cube-2d-game__action" type="button" disabled={!controller.canUndo()} onClick={() => void g.run(() => controller.undo())}>Undo</button>{g.result && !g.resultOpen ? <button className="cube-2d-game__action" type="button" onClick={() => g.setResultOpen(true)}>Game result</button> : null}<button className="cube-2d-game__action cube-2d-game__new-game" type="button" onClick={onRequestNewGame}>New game</button></div>
    {g.vm.phase === 'endgame' ? <section className="endgame-panel cube-2d-game__endgame" aria-labelledby="cube-endgame-title"><div><h2 id="cube-endgame-title">Manual endgame classification</h2><p>Select a stone group on the Cube surface, then choose Alive, Dead, or Seki.</p></div>{g.groups.length ? <><div className="endgame-progress" aria-live="polite">Classified {g.classified} of {g.groups.length}</div>{g.selected ? <div className="endgame-selection"><div className="endgame-selection__identity"><span className={`stone-chip stone-chip--${g.selected.color}`} aria-hidden="true" /><div><strong>Selected group</strong><span>{g.selected.points.length} {g.selected.points.length === 1 ? 'stone' : 'stones'}</span></div></div><div className="endgame-statuses" role="group" aria-label="Selected group status">{CUBE_ENDGAME_STATUSES.map((status) => <button type="button" key={status} className={g.decisions[g.selected!.id] === status ? 'is-selected' : undefined} aria-pressed={g.decisions[g.selected!.id] === status} onClick={() => g.setDecisions((current) => ({ ...current, [g.selected!.id]: status }))}>{cubeEndgameStatusLabel(status)}</button>)}</div></div> : <p className="endgame-empty">Select a stone group directly on a Cube face.</p>}</> : <p className="endgame-empty">There are no stone groups to classify.</p>}<button className="finish-game-button" type="button" disabled={!g.allClassified || Boolean(g.transition)} onClick={() => void g.finish()}>Calculate final score</button></section> : null}
    {g.result && g.resultOpen ? <GameResultDialog result={g.result} onClose={() => g.setResultOpen(false)} /> : null}{g.feedback ? <p className="cube-2d-game__feedback">{g.feedback}</p> : null}
  </section>;
}
